version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    reviewers:
      - "echoblag"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    reviewers:
      - "echoblag"
